controller_node:
  ros__parameters:
    use_sim_time: true
    controller_types: [serest]
    serest:
      rt_freq: 30.0
      plugin: easynav_serest_controller/SerestController
      allow_reverse: true
      max_linear_speed: 0.8
      max_angular_speed: 1.2
      v_progress_min: 0.08
      k_s_share_max: 0.5
      k_theta: 2.5
      k_y: 1.5
      goal_pos_tol: 0.1
      goal_yaw_tol_deg: 6.0
      slow_radius: 0.80
      slow_min_speed: 0.02
      final_align_k: 2.5
      final_align_wmax: 0.8
      corner_guard_enable: true
      corner_gain_ey: 1.8
      corner_gain_eth: 0.7
      corner_gain_kappa: 0.4
      corner_min_alpha: 0.35
      corner_boost_omega: 1.0
      a_lat_soft: 0.9
      apex_ey_des: 0.05

localizer_node:
  ros__parameters:
    use_sim_time: true
    localizer_types: [gps_localizer]
    gps_localizer:
      rt_freq: 30.0
      plugin: easynav_gps_localizer/GpsLocalizer
      gps_topic: /gps
      imu_topic: /mavros/imu/data
      base_frame: base_link
      world_frame: map

maps_manager_node:
  ros__parameters:
    use_sim_time: true
    map_types: [dummy]
    dummy:
      plugin: easynav_maps_manager/DummyMapsManager

planner_node:
  ros__parameters:
    use_sim_time: true
    planner_types: [costmap_planner]
    costmap_planner:
      freq: 0.5
      plugin: easynav_costmap_planner/CostmapPlanner
      robot_radius: 0.25
      cost_factor: 3.0

sensors_node:
  ros__parameters:
    use_sim_time: true
    forget_time: 0.5
    sensors: [laser1, gps1]
    perception_default_frame: odom
    laser1:
      topic: /scan
      type: sensor_msgs/msg/LaserScan
    gps1:
      topic: /gps
      type: sensor_msgs/msg/NavSatFix

system_node:
  ros__parameters:
    use_sim_time: true
    position_tolerance: 0.3
    angle_tolerance: 0.15
